server:
  port: 8090
spring:
  sql:
    init:
      mode: ALWAYS
  application:
    name: spring-boot-docker
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: false    
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url:  ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookdb}
    hikari:
      poolName: Hikari
      auto-commit: false




